# This is a sample build configuration for Java – Gradle.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10
clone:
    depth: full
pipelines:
    branches:
        master:
            - step: # build project and push to HEROKU.
                script:
                    - npm i
                    - npm run build
                    - apt-get update && apt-get install -y git
                    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master