import webpack from 'webpack';
import path from 'path';
import {CleanWebpackPlugin} from 'clean-webpack-plugin';
import Analyzer from 'webpack-bundle-analyzer';
import Visualizer from 'webpack-visualizer-plugin';
import MiniCSSExtractPlugin from 'mini-css-extract-plugin';
import OptimizeCSSAssetsPlugin from 'optimize-css-assets-webpack-plugin';
import CopyPlugin from 'copy-webpack-plugin';
import WorkboxPlugin from 'workbox-webpack-plugin';

const srcPath = path.resolve('./src');
const distPath = path.resolve('./dist');
const nodeDir = path.resolve('./node_modules');

export default {
  entry: {
    polyfill: 'babel-polyfill',
    app: './src/app/App.jsx',
  },
  output: {
    path: distPath,
    filename: '[name].js',
    publicPath: '/',
  },
  node: {
    net: 'empty', // sockjs and stompjs
  },
  performance: {
    hints: false, // use 'warning' to webpack notifies you of assets and entry points that exceed a specific file limit
  },
  stats: {children: false}, // hide MiniCSSExtractPlugin information printed when build
  optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {test: /\.s?css$/, name: 'styles', chunks: 'all'},
        react: {test: /[\\/]node_modules[\\/]react-dom[\\/]/, name: 'react', chunks: 'initial'},
      },
    },
  },
  plugins: [
    new CleanWebpackPlugin(),
    new Analyzer.BundleAnalyzerPlugin({
      analyzerMode: 'static', reportFilename: '../statistics/tree.html', openAnalyzer: false,
    }), // generate tree.html
    new Visualizer({filename: '../statistics/stats.html'}), // generate stats.html
    new MiniCSSExtractPlugin(), // create a separated file for css
    new OptimizeCSSAssetsPlugin(), // remove duplicated css classes generated by sass-loader
    new webpack.DefinePlugin({
      'process.env': {
        API_URL: JSON.stringify(process.env.API_URL),
      },
    }),
    new CopyPlugin({patterns: [{from: './src/manifest.json', to: distPath}]}),
    new WorkboxPlugin.GenerateSW({
      clientsClaim: true,
      skipWaiting: true,
      navigateFallback: '/index.html',
      runtimeCaching: [
        {
          urlPattern: /^https:\/\/drive\.google\.com\/uc.*/, // cache all drive images responses
          handler: 'StaleWhileRevalidate',
        },
      ],
    }),
  ],
  resolve: {
    extensions: ['*', '.js', '.jsx'],
    alias: {
      app: `${srcPath}/app`, // allow to use import with absolute path (example 'app/')
      assets: `${srcPath}/assets`, // allow to use import with 'assets/'
      stompjs: `${nodeDir}/stompjs/lib/stomp.js`, // allow to use import Stomp from 'stompjs';
    },
  },
  module: {
    rules: [
      // babel
      {test: /\.(js|jsx)?$/, exclude: [/node_modules/], use: 'babel-loader'},
      // index
      {test: /index.html$/, use: 'file-loader?name=[name].[ext]'},
      // fonts
      {test: /\.(eot|woff|woff2|ttf)$/, use: 'file-loader?name=fonts/[name].[ext]'},
      // assets
      {test: /\.(png|jpg|gif)$/, use: 'file-loader?name=assets/[name].[ext]'},
      // svg
      {test: /\.svg$/, use: '@svgr/webpack'},
      // sass
      {
        test: /\.(scss|css)$/, use: [
          MiniCSSExtractPlugin.loader,
          'css-loader',
          {loader: 'postcss-loader', options: {plugins: [require('autoprefixer')()]}}, // add vendor prefix (-webkit)
          'sass-loader',
        ],
      },
    ],
  },
};